apiVersion: apps/v1
kind: Deployment
metadata:
  name: distributor
  namespace: tempo
spec:
  minReadySeconds: 10
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: distributor
      name: distributor
      tempo-gossip-member: "true"
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
  template:
    metadata:
      annotations:
        config_hash: d0ff8e7d357d2e9102e1df9da4a79286
      labels:
        app: distributor
        name: distributor
        tempo-gossip-member: "true"
    spec:
      containers:
      - args:
        - -config.file=/conf/tempo.yaml
        - -mem-ballast-size-mbs=1024
        - -target=distributor
        image: grafana/tempo:latest
        imagePullPolicy: IfNotPresent
        name: distributor
        ports:
        - containerPort: 14250
          name: jaeger-grpc
        - containerPort: 4317
          name: otlp-grpc
        readinessProbe:
          httpGet:
            path: /ready
            port: 3200
          initialDelaySeconds: 15
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "3"
            memory: 5Gi
          requests:
            cpu: "1"
            memory: 2Gi
        volumeMounts:
        - mountPath: /conf
          name: tempo-conf
        - mountPath: /overrides
          name: overrides
      terminationGracePeriodSeconds: 60
      volumes:
      - configMap:
          name: tempo-distributor
        name: tempo-conf
      - configMap:
          name: tempo-overrides
        name: overrides
