apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    name: ingester
  name: ingester
  namespace: tempo
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      name: ingester
